name: Compressed Size

on:
  pull_request:

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Track HTML/CSS/JS in repo (no build step yet)
          pattern: "./**/*.{html,css,js}"
          exclude: "{**/.git/**,**/.github/**,**/node_modules/**}"
          compression: brotli
