name: Lighthouse CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli@0.14.0

      - name: Start static server
        run: npx http-server . -p 8080 -c-1 &

      - name: Wait for server
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/ > /dev/null; then
              echo "Server is up"; break; fi; sleep 1; done

      - name: Run Lighthouse CI
        run: |
          lhci collect --url=http://localhost:8080/ --numberOfRuns=1 --settings.chromeFlags='--no-sandbox' --settings.formFactor=desktop --settings.screenEmulation.disabled
          lhci assert --config=./.lighthouse/budget.json || true

      - name: Upload LHCI results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: ./.lighthouseci
